import type { ChildDashboard } from '../types/api';

export const childDashboardMock: ChildDashboard = {
  child: {
    id: 'emma-demo',
    firstName: 'Emma',
    avatarEmoji: '🧒',
    level: 7,
    title: 'Exploratrice des mots',
    stars: 125,
    streakDays: 7,
  },
  progress: {
    percent: 68,
    starsEarned: 125,
    objectivesCompleted: 17,
    streakDays: 7,
  },
  dailyGoal: {
    id: 'goal-two-activities',
    title: 'Mon objectif du jour',
    description: 'Termine 2 activités et gagne 20 étoiles !',
    currentCount: 1,
    targetCount: 2,
    rewardStars: 20,
  },
  activities: [
    {
      id: 'mental-math',
      subject: 'math',
      title: 'Calcul mental',
      description: 'Réchauffe ton cerveau avec des petits calculs.',
      progressPercent: 72,
      status: 'in_progress',
      rewardStars: 8,
      route: '/activites/calcul-mental',
      icon: '🧮',
    },
    {
      id: 'multiplication-tables',
      subject: 'multiplication',
      title: 'Tables de multiplication',
      description: 'Révise les tables et deviens championne.',
      progressPercent: 68,
      status: 'in_progress',
      rewardStars: 10,
      route: '/activites/tables-multiplication',
      icon: '✖️',
    },
    {
      id: 'poetry',
      subject: 'poetry',
      title: 'Poésie',
      description: 'Écoute, mémorise puis récite en douceur.',
      progressPercent: 42,
      status: 'in_progress',
      rewardStars: 12,
      route: '/activites/poesie',
      icon: '🎙️',
    },
    {
      id: 'dictation',
      subject: 'dictation',
      title: 'Dictée',
      description: 'Écoute la phrase puis écris-la dans ton cahier magique.',
      progressPercent: 28,
      status: 'not_started',
      rewardStars: 6,
      route: '/activites/dictee',
      icon: '✍️',
    },
  ],
  recentBadges: [
    { id: 'fast', title: 'Rapide', description: '3 réponses justes de suite', icon: '⚡', unlocked: true },
    { id: 'persistent', title: 'Persévérante', description: '7 jours de suite', icon: '🔥', unlocked: true },
    { id: 'apprentice', title: 'Apprentie', description: 'Première mission terminée', icon: '🌟', unlocked: true },
  ],
  activeChallenge: {
    id: 'champions',
    title: 'Défi des champions',
    description: 'Réussis 5 défis cette semaine.',
    currentCount: 3,
    targetCount: 5,
    rewardStars: 30,
  },
  reminders: [
    { id: 'quiz', title: 'Quiz du jour', description: 'Un mini quiz t’attend.', kind: 'quiz' },
    { id: 'homework', title: 'À ne pas oublier', description: 'Revoir la table de 7.', kind: 'homework' },
  ],
};
